# Generated by Django 5.2.8 on 2025-11-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_remove_appointment_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
