# Generated by Django 5.2.8 on 2025-11-21 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0005_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective_notes', models.TextField(blank=True, help_text='Patient-reported symptoms, history')),
                ('objective_findings', models.TextField(blank=True, help_text='Vitals, physical exam findings')),
                ('diagnosis', models.CharField(blank=True, max_length=255)),
                ('treatment_plan', models.TextField(blank=True, help_text='Therapies, interventions decided')),
                ('follow_up_instructions', models.TextField(blank=True, help_text='Monitoring, next visit guidance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='clinic_app.appointment')),
            ],
        ),
    ]
